

# Georgia State University {-}

## College of Education and Human Development Research, Measurement and Statistics Program  {-}

## Program Mission  {-}

Our masters programs in Educational Research prepares students to conduct research and evaluate programs in kindergarten through 12th grade schools, colleges and universities, and other settings (for example: government, healthcare and public health). The Ph.D. in Educational Policy Studies allows students to examine the philosophy and practice of education and to develop skills in both the methodology and the study of educational practice. Students will prepare to become policymakers and examiners of policy and the effects of policy on education. Students can complete a concentration in Research, Measurement and Statistics as preparation to investigate research methodologies, to conduct research related to schools, and to conduct and critique research in educational practice, policy and administration. Students develop knowledge and skills in qualitative and quantitative research and evaluation methods.

## Faculty and Research Interests  {-}
Faculty interests include research on teacher effectiveness and persistence, the effects of peers on student outcomes and program evaluation, applied measurement and quantitative methods in education, research in multilevel modeling and computerized adaptive testing, and methods for systematic review and meta-analysis.

## General Curriculum  {-}
The degree programs in Research, Measurement, and Statistics include an M.S. in educational research; an online M.S. in educational research; and a Ph.D. in educational policy studies. Students who decide to pursue a Ph.D. in educational policy must have a master's degree.

## Admissions Criteria  {-}
The admissions criteria for the M.S. in educational research program are the following:

- Complete online application
- Application fee of $50
- Statement of purpose to upload with the application
- Resume (upload with the application)
- Two letters of recommendation
- Official transcript: minimum 2.5 undergraduate GPA required for admission. Must submit transcripts from all colleges and universities attended.

* Due to the onset of the pandemic, GRE scores are currently not required for the master's program.

The admissions criteria for the Ph.D. program in educational policy studies are the following:

- Complete online application
- Application fee of $50
- Statement of purpose to upload with the application
- Resume (upload with the application)
- Two Letters of Recommendation (recent letters from persons who can evaluate academic promise such as professors)
- Must have completed a master’s level degree
- Official transcript: minimum 3.30 graduate GPA required for admission. Must submit transcripts from all colleges and universities attended.

*Due to the onset of the pandemic, GRE scores are currently not required for the doctoral program.

## Admissions Timeline  {-}
The application deadlines for the M.S. in educational research program (and the online version) are March 1st, October 15th, and March 1st for Fall, Spring, and Summer respectively. The application deadlines for the Ph.D. in educational policy studies program are January 15th for Fall. The doctoral program does not admit in Spring nor Summer.

## Funding  {-}
Many of our faculty work on grant-funded projects that hire our students as graduate research assistants. For incoming doctoral students, there is the opportunity to apply for the Dean’s Research Doctoral Fellowship. For international and out-of-state students, tuition waivers are available to reduce the cost of tuition to the in-state rate.

## Mentoring / Student Engagement Philosophy  {-}
Every incoming graduate student is assigned a faculty adviser upon entry into the program. Students are able to change their assigned advisor at any point in time, such as when a dissertation topic has been decided, if they see that another faculty advisor would be a better fit for that topic. The department also hosts student mixers each semester as a way to promote engagement and collaboration.

## Where Past Graduate Students Are Now  {-}
The past graduates in the program have the following careers:

- Educational researcher
  - Utilize quantitative and qualitative methods to formatively and summatively evaluate science education programs throughout the U.S.
  - Code qualitative data from Federal Register Rule submissions.
- Department of Juvenile Justice
- USG Board of Regents
- Director of Institutional Research, Agnes Scott College
- Policy and Planning Development Specialist, Georgia Department of Juvenile Justice
- Education Data and Statistics Analyst, Georgia Department of Education
- Research Analyst, Georgia Tech’s Office of Institutional Research
- Education Data and Statistics Analyst at Georgia Department of Education
  - Teacher and Leader Effectiveness Division
  - Data cleaning of large student-level statewide datasets using either Excel or SPSS
  - Large data manipulation such as sorting, merging, aggregating, splitting, and restructuring
