
# Penn State University {-}


## PhD in Human Development and Family Studies Methodology Specialization  {-}

## Program Mission  {-}
The PhD program in Human Development and Family Studies (HDFS) is designed to help students learn and generate research in cutting-edge approaches to the study of individuals and families across the life span. In the methodology specialization this entails the development and application of new methodological approaches. This work spans all levels of analysis from the biological (genetics, physiology) to the social context (schools, families, neighborhoods, and the workplace), across many timescales (cells to society, milliseconds to millennia, cradle to grave). These methods are often applied to understand development in childhood, adulthood and old age; for the study of individual and interpersonal processes like emotion and learning; and for the development and evaluation of prevention and intervention programs. Students interested in quantitative methodology may be particularly interested in the Methodology Research Specialization and [dual-title](https://hhd.psu.edu/hdfs/graduate/dual-title-programs) PhD programs in HDFS and Social Data Analytics, Demography or Social and Behavior Neuroscience.



## Faculty and Research Interests  {-}

There are six core faculty members in the Quantitative Developmental Systems Methodology Core:  

- 	Sy-Miin Chow  
- 	Peter Molenaar   
- 	Zita Oravecz  
- 	Timothy Brick  
- 	Michael Hunter  
- 	Zachary Fisher  

with broad expertise in methods for understanding human health and behavior at multiple levels and time-scales. Specific interests include intensive longitudinal data collection methods (e.g. ecological momentary assessments, smartphone sensors, wearable and digital health measures, geospatial data); associated analyses such as structural equation modeling, dynamical systems, Bayesian modeling and estimation, data mining and machine learning approaches, intervention optimization and real-time adaptive intervention, network analysis, and statistical programming; and applications of these methods to diverse areas, including

lifespan development, affect, cognitive, physiology, behavioral genetics, neurological (e.g. fMRI, fNIRS) activity, family, and health processes.




## General Curriculum  {-}
Although students will develop areas of specialization in their study, HDFS is a single department and grants a single degree. Thus, all students complete a common core of coursework in their first year, covering the broad substantive themes of the department: Individual Development, Family Studies, Prevention and Intervention, and Developmental Methodology. While some students will elect to specialize in methodology, all students are also expected to develop strong skills in research methods, a hallmark of our graduate training. All students complete a common four-course methodology sequence, which focuses on research design, measurement, and statistics, with a strong emphasis on statistical approaches for modeling development and change over time, and complete two additional methods-focused courses of their own choosing. In consultation with their advisors, students fulfill the remaining course credit requirements through the selection of electives individually tailored to their research interests. These courses include seminars offered in the department, as well as courses offered in other departments throughout Penn State such as Demography, Women's Studies, Statistics, Psychology, Sociology, Information Services and Systems, Computer Science, and Communication Arts and Sciences. Students may wish to consider additional specialization through a graduate minor, a concurrent degree (e.g. master’s degree in statistics) or a dual-title Ph.D.


## Admissions Criteria  {-}
The two most important requirements are (1) evidence of academic aptitude, including strong communication and quantitative skills; and (2) a good "substantive fit" between the applicant's interests and those of our faculty. We are interested in admitting students whose interests cut across the activities or work of several faculty members. HDFS has a strong collaborative culture and although students will be placed with a primary faculty advisor, it is not uncommon for students to work closely with more than one faculty member during their graduate training, or to change primary advisors as their research interests evolve. GRE scores are no longer required as of the Fall 2022 admissions cycle.  

Applicants are required to submit:  

- 	A scientific writing sample.  
- 	Official transcripts.  
- 	Curriculum Vitae or Resume (optional).  
- 	Statement of Professional and Career Plans.   
- 	DEI Statement   
- 	Three letters of recommendation.   

When you are ready to apply visit the [Grad School Admissions and Program Information Portal](https://gradschool.psu.edu/graduate-admissions/how-to-apply/new-applicants/), which will guide you through the materials required by the University, as well as program-specific required documents.  



## Admissions Timeline  {-}
Applications to the PhD program are due by December 1st.


## Funding  {-}
All students admitted to the graduate program in HDFS are provided funding for their graduate study. Funding could be in the form of a fellowship or an assistantship, but both include (a) the full cost of tuition, (b) a stipend for living expenses, and (c) a health insurance subsidy. Tuition costs are paid directly by the fellowship or assistantship and therefore the student does not have the responsibility of paying the tuition. Funding is guaranteed for a minimum of 4 years, with the expectation that funding can be provided for as long as needed to complete the program, presuming the student remains in good standing and is in residence in State College.


## Mentoring / Student Engagement Philosophy  {-}
Advisor assignments are made based of a mutual interest on the part of the student and faculty member(s). Applicants are strongly encouraged to identify faculty members with whom they would be interested in working in their applications. Prospective advisors are consulted during the admissions process, and may reach out to applicants for telephone interviews. During the Admissions Weekend, prospective students will be given the opportunity to meet with the individual faculty members to discuss research and training opportunities.


## Where Past Graduate Students Are Now  {-}
Graduates from HDFS have been successful in both academic and industry settings. A few recent examples include:  
- 	Associate Professor, UC Davis  
- 	Assistant Professor, Purdue University  
- 	Assistant Professor, University of Pennsylvania  
- 	Assistant Professor, Arizona State University  
- 	Assistant Professor, Claremont Graduate University  
- 	Research Scientist, ACTNext  
- 	Visualization Specialist, University of Virginia  
- 	Data Scientist, Uber  
- 	Data Scientist, Penguin Random House  
- 	Biostatistician, Novartis  
- 	Director, The Center for Implementation  
- 	Senior Research Analyst, Office of Planning, US HHS  
- 	Survey Researcher, Mathematica Policy Research  
- 	Analyst, Abt Associates Inc  


