
# UCLA School of Education {-}

## Social Research Methodology at the UCLA {-}


https://seis.ucla.edu/departments-and-degrees/department-of-education/social-research-methodology-division 

## Program Mission  {-}

The [Social Research Methodology (SRM)](https://seis.ucla.edu/departments-and-degrees/department-of-education/social-research-methodology-division) Division is committed to the study and practice of methods of inquiry in educational and social research. The SRM curriculum emphasizes conceptualization of applied problems, design and conduct of research and evaluation, development and application of new methodological techniques, and analysis and interpretation of data in the context of educational theory and practice, and critical examination of research based claims. The division offers methodological concentrations in 1) educational statistics and educational measurement, 2) evaluation, and 3) qualitative methodology that aim to prepare students to:  
-	Critically examine research and evaluation  
-	Develop data collection designs and instruments  
-	Conduct conceptual and statistical analyses appropriate to the field of education as well as other behavioral and social sciences  

The SRM Division works with the SRM Evaluation and Assessment Group, [CRESST](https://cresst.org/) (National Center for Research on Evaluation, Standards, and Student Testing), and the University of California Educational Evaluation Center [(UCEC)](https://ucec.gseis.ucla.edu/).



## Faculty and Research Interests  {-}


The SRM Division focuses on partnering methodological innovation with practical applications. The faculty specialize in either statistical inferential, or qualitative-interpretive methods of research, and a multiple- methods approach to address the complex dimensions of research in social science and education. As a faculty, we are interested in the multiple forms of inquiry about educational questions, the development of critically reflective/reflexive habits of mind about research, and the way to effectively represent that research in writing. 





## General Curriculum  {-}


The SRM division offers two degree programs: the M.A. and the Ph.D. SRM also offers a certificate program in Advanced Quantitative Methodology in Educational Research which is open to all UCLA graduate students.






## Admissions Criteria  {-}


Admission to the SRM Division is granted on a competitive basis. Review of dossiers is holistic and takes into consideration the unique combination of strengths and background of each candidate, in relation to their specific areas of interest. However, typical qualifications of admitted Ph.D. Students include:   
-	The currently specified requirements of the Graduate Division of UCLA.   
-	GPA above 3.0 for all upper-division undergraduate and graduate courses.     
-	GRE combined Verbal and Quantitative score in the 310-320 range, and higher.   
-	A primary career interest in research and teaching in institutions of higher education, working in a research or policy institute, or in student affairs or institutional research or leadership.   
- Realistic knowledge of the field and profession, and appropriate interests and career objectives aligned to those of the faculty in the program.   




## Admissions Timeline  {-}
Deadline for applications: Dec 1st 
Admissions Decisions: February
Open house for admitted students: March



## Funding  {-}


SRM students are typically funded to be engaged in their program full-time on campus through part-time teaching or research assistantships that cover education fees and provide a monthly salary. Teaching assistantships for SRM courses are assigned each year by the SRM faculty. Individual faculty members are also a resource in finding appropriate research positions. Students are responsible for planning ahead of time for fellowships and research and teaching assistantships in order to avoid gaps in funding.  Special fellowships are coordinated through the Office of Student Services, and involve a separate application process. Students wishing fellowship support must apply for it each year (with the exception of multi-year fellowships like Spencer or Cota-Robles). Cota-Robles fellowship recipients should be engaged in research with faculty for at least years 2 and 3 


## Mentoring / Student Engagement Philosophy  {-}


Upon admission to the program, students are assigned a faculty advisor. This is determined by matching the research interests of each student with those of a faculty member. The advisor may serve as an academic counselor, information resource, or otherwise assist the student's progress through the program. The primary responsibilities of the faculty advisor are to approve the student's academic program, to advise students on particular courses of study, and, along with the student, to initiate any petitions for change in degree status or program. At any time, students may change advisors without reprisals. If a student wishes to change advisors, s/he should consult both faculty members before undertaking such action and then should inform the Division Head and the Office of Student Services (OSS) of the change. Students are expected to be proactive in scheduling to meet with their advisor at least twice per quarter. 


## Where Past Graduate Students Are Now  {-}


SRM Graduates have been placed quickly at top universities including: UC Berkeley, Northwestern University, UCLA, Stanford University, UC Riverside, California State University, Portland State University, Indiana University, University of Colorado, University of Delaware, University of Newcastle, University of Florida, University of Maryland, University of Massachusetts, and University of Hawaii. Other students hold positions at research organizations and agencies such as the American Council on Education, American Institutes of Research, the Association of American Medical Colleges, The RAND Corporation, Centers for Disease Control, Educational Testing Service, Stanford Research Institute, and ABT Associates, among others. 


