
# UCLA Quantitative Psychology {-}

## Quantitative Psychology Program {-}

https://www.psych.ucla.edu/grads/areas-of-study/quantitative-psychology

## Program Mission  {-}
The quantitative major at UCLA Psychology is a highly individualized program providing ample opportunity for one-on-one interaction with faculty. Students concentrating in quantitative psychology will generally fit into one of two categories. The first of these consists of students possessing excellent mathematical backgrounds and strong theoretical interests in technical problems in measurement theory, statistics, and modeling. The second group of students typically has more applied interests. While the latter group of students have preparation in mathematics, these students are more oriented toward the use of psychometric and analytic techniques in substantive research. Some students find it compatible to give equal attention to both these major aspects of the program. Students in the quantitative program are strongly encouraged to collaborate with faculty in substantive areas of psychology in addition to their quantitative training. These areas include but are not limited to couples analysis, longitudinal and diary data, health outcomes, and the biological underpinnings of psychopathology.


## Faculty and Research Interests  {-}
Quantitative psychology provides an opportunity for students to specialize in measurement, methodology and research design and analyses relevant to data in the social sciences.
Psychology faculty currently includes Han Du, Craig Enders, Amanda Montoya, and Steven Reise. Key areas of interest among the faculty are structural equation modeling, item response theory, multilevel modeling, and the analysis of fMRI data. You can see each faculty's page by following this link: https://www.psych.ucla.edu/faculty/quantitative





## General Curriculum  {-}
Our program does not offer a masters only track, all students are admitted directly into the PhD program. However, students can receive an MA in Psychology after completion of required coursework and their first-year project (251 series).

Required coursework for the PhD include the introductory statistics series (250ABC), first year research project series (251ABC), quantitative aspects of assessment (255A), introduction to multilevel modeling (256A), multivariate analysis with latent variables (M257), and special topics in psychological statistics (258). Students must also enroll in the Quantitative Psychology Seminar (249) for at least 6 quarters. Students must also complete 8 credits (2 quarters) of the Quantitative Psychology Practicum, which provides training and experience with statistical consulting.

After completing required coursework but prior to proposing their dissertation research, students complete their comprehensive exam (typically 3rd year) which can take any of three forms designed to help students gain experience relevant to their career goals. Students can 1) Write responses to questions developed from a reading list, 2) develop materials for a graduate-level course in methodology, or 3) prepare a grant application.

For more information see our graduate student handbook: https://ucla.app.box.com/s/27yt5n0xr6q1qtskht4z2nl5wlws93p5




## Admissions Criteria  {-}
A Bachelor’s degree (Bachelor's or Arts or Bachelor's of Sciences) or its equivalent from an accredited university worldwide is not required to apply to our program, but is required to enter our program. A Master’s degree is not required to apply or enter our program.
Applications are considered only for the Fall quarter. The department regards a broad undergraduate background in the behavioral, biological, physical, and social sciences as the best preparation for graduate study in psychology. It is desirable but not required to have majored in psychology. A course in college level math or statistics is required.In addition, very careful consideration is given to your Statement of Purpose, research experience and letters of recommendation. An outstanding record in any one of these areas, especially demonstrated achievement in research endeavors, may compensate for poorer performance in another.
Research experience--gained as a laboratory assistant, through independent studies or prior graduate work, or by writing a senior or honors thesis--is a valuable asset for all applicants to the Ph.D. program.The Department seeks a diverse student body. Cultural diversity and socioeconomic background are strongly considered when assessing candidates' potential for graduate study. Applicants are encouraged to include information on their background, achievements, obstacles, and special contributions to the discipline on their application. For the Fal 2021 cohor, GRE scores will not be required or considered for admissions.
For more on admissions criteria please see https://www.psych.ucla.edu/graduate/prospective- students/preparation




## Admissions Timeline  {-}
We admit students on a yearly cycle, entering in Fall semester. Applications are due December 1st, 2021 for admission in Fall of 2022. Interviews will take place between January - March.
Admissions decisions will be made prior to the April 15th national deadline. Admissions decisions may come on a rolling basis, so please wait to hear from the department about the decision.




## Funding  {-}
All students entering our program are guaranteed financial support for at least five years with a stipend of $24,000/year + in-state tuition/fees/insurance. Most funding is in the form of graduate assistantships (appointments of at least 50% of full-time equivalent), which include teaching assistantships and research assistantships. First year students TA at 25% for one quarter during their first year, and otherwise have no other required assistantships to receive their funding.
First year students also have out-of-state tuition covered by the department; however, they are expected to apply for residence after their first year in California. International students must draft a plan for covering international student tuition, typically involving a funding commitment

from faculty within the department. We have a variety of internal fellowships to support students including the [Cota-Robles ](https://grad.ucla.edu/funding/financial-aid/funding-for-entering-students/eugene-v-cota-robles-fellowship/) (supporting URM students), [Graduate Research Mentorship Fellowship, Graduate Summer Research Mentorship Fellowship](https://grad.ucla.edu/funding/financial-aid/funding-for-continuing-students/graduate-research-mentorship-program/). Additionally students at UCLA are very competitive for the National Science Foundation Graduate Research Fellowship. UCLA also allows students on fellowship to TA on top of their fellowship to supplement their income. For more on funding available through UCLA please see https://grad.ucla.edu/funding.



## Mentoring / Student Engagement Philosophy  {-}
Our program focuses on a mentorship and co-mentorship model, where students entering the program are assigned one or more faculty mentors. Graduate students complete a first-year project (251 series) which involves a supervisor and a reader (both department faculty), to encourage students developing strong relationships with multiple faculty. Students frequently work with their mentorship, other area faculty, other departmental faculty, and across campus to develop strong collaborative skillsets. In particular, many departmental faculty in search of statistical support may hire quantitative psychology students as Graduate Research Assistants to foster a collaborative relationship in a substantive area. Students are required to identify a committee of 3 - 4 faculty members for both their qualifying exams and dissertation proposal and defense. So we encourage students to collaborate with many faculty in order to identify strong committee members in preparation for these milestones.




## Where Past Graduate Students Are Now  {-}
Graduates from our programs can be found in academic and industry settings. A few recent examples include:  
⦁	Wes Bonifay, Assistant Professor, University of Missouri, College of Education, Class of 2015  
⦁	Andrew Moskowicz, Analyst, Roku Inc (Previously at Hulu), Class of 2017  
⦁	Brian Keller, Assistant Professor, University of Texas Austin, Department of Educational Psychology, Class of 2019.  
⦁	Maxwell Mansolf, Project Scientist @ UC-Riverside, Lecturer @ UCLA, Class of 2019  



