
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# University of Connecticut {-}

## Graduate programs in Research Methods, Measurement, and Evaluation (RMME) Program Mission {-}

## Program Mission  {-}
The mission of RMME is to conduct high quality research, training, and service in the areas of statistical methods (including latent variable and multilevel modeling), educational and psychological measurement (including psychometrics), research design and quantitative research methodology, and program evaluation. Our rigorous graduate curriculum provides training to students who wish to become psychometricians, quantitative methodologists, and evaluation professionals in social, behavioral, or educational fields, as well as for those who wish to pursue academic careers as faculty, teaching coursework in quantitative research methods, measurement, or program evaluation.


## Faculty and Research Interests  {-}
We currently have 5 full-time faculty teaching in our program. Faculty research interests span a wide range of topics in the areas of psychometrics, measurement, evaluation and applied statistics (including modeling). Example research interests of faculty include latent variable modeling, methods for reproducible science, instrument design, assessing and measuring school effectiveness, research on evaluation, measurement of implementation fidelity, accounting for multi-level structures in causal observational studies and generalizing the results of randomized controlled trials to target populations. Additional information is available here:
https://rmme.education.uconn.edu/selected-current-research-projects-for-mea-faculty/




## General Curriculum  {-}
We offer on-campus Masters and Ph.D. programs. Students in the Ph.D. program may elect to receive a Masters degree on the way to the Ph.D. We have also had strong Master students transfer to the Ph.D. program in the past.
Additionally, we have two fully-online programs: A 30 credit MA degree and a 12 credit certificate in program evaluation.
Our curriculum includes courses in educational statistics, measurement, program evaluation, research design, psychometrics, and modeling.



## Admissions Criteria  {-}
At the Ph.D. level, we look for evidence that the student will be successful in both the coursework and the sustained independent research required to complete a doctorate. Although academic and research indicators such as undergraduate coursework, grades, and research experience enter into the decision making process, one of the most important elements of the application packet is the personal statement, which provides information about the students’ research interests, potential fit with the program, and future academic
and career goals.
 


## Admissions Timeline  {-}
PhD applications are due December 1st for full funding consideration. Masters applications are accepted on a rolling basis until June 1.





## Funding  {-}
The PhD program offers funding in the form of graduate assistantships to full-time PhD students. These are awarded on a competitive basis. Research and teaching assistantships fully cover the cost of tuition and also provide group health insurance. Typically, we are able to fund 3-4 incoming PhD students per year, and historically, such students are funded for the duration of their PhD program, as long as they maintain adequate academic progress and perform satisfactorily in their assigned assistantship duties. Occasionally, there is funding available for on-campus Masters students. The most competitive incoming students also compete for University fellowships and College level awards. Some students secure external funding from government or private agencies to support them as they pursue their degrees. Many of our students participate in paid summer internships at least once during the PhD program, and summer assistantships are often available to continue work on externally funded research projects over the summer break.


## Mentoring / Student Engagement Philosophy  {-}

At the PhD level, students receive a great deal of individualized mentoring from their major advisor and program faculty. Generally, the first year or two of the PhD program is more course heavy, as students develop competencies across our six areas. During this time, students generally join research projects led by faculty. As students progress through the program, they take increasing ownership over research projects, under the guidance and mentorship of RMME faculty. They also develop an academic identity and an area of research specialization in a specific area within RMME. The dissertation represents the culmination of the students’ development as an independent researcher.






## Where Past Graduate Students Are Now  {-}
Our Ph.D. graduates have been employed in a variety of positions in academia, government, non-profit and for-profit companies. A partial list of present employers of program graduates is below:
- Measurement Fellow, Law School Admissions Council  
- Connecticut State Department of Education Performance Office.  
- Associate Professor, Texas A\&M  
- Assistant Professor, McGill University (Dr. Jessica Flake, one of the organizers of this event, is a graduate of our PhD program!)  
-	Assistant Professor, Yale University  
- Statistician, Yale University  
⦁	Senior Research Associate, Adelphi Values  
⦁	Associate Director of Global Evidence and Outcomes, Takeda Pharmaceuticals.  
⦁	Analyst, U.S. Government Accountability Office  



