# University of Georgia  {-}

## Graduate Programs in Quantitative Methodology  {-}

 https://coe.uga.edu/academics/concentrations/quantitative-methodology

## Program Mission  {-}
-	Increase the effectiveness of research and assessment in the social sciences by advancing quantitative methodology through state-of-the-art research  
-	Train students to become high-quality researchers in the areas of psychometrics, statistics, measurement, and assessment.  



## Faculty and Research Interests  {-}
We have 6 full-time tenure-track faculty with research interests including educational measurement and policy, item response theory, diagnostic measurement models, structural equation modeling, multilevel modeling, psychometrics, computer adaptive testing, and more. Many faculty members are engaged in funded collaborative educational projects employing advanced quantitative methods.




## General Curriculum  {-}
We have both a master’s and PhD program. The program curriculum is flexible with only a few required courses. In consultation with your advisor(s), students choose other courses to meet their needs and interests. Students typically focus on methods courses, but also take a variety of courses from different departments and areas of study.






## Admissions Criteria  {-}


-	Strong background (or potential) for research in quantitative methods
-	Research interests aligned with program/faculty


 


## Admissions Timeline  {-}


All applications are due December 1 for funding consideration. Decisions are made in February-March.






## Funding  {-}


Students are funded through a variety of research and teaching assistantships.

## Mentoring / Student Engagement Philosophy  {-}


Students work closely with faculty early and often, engaging in research activities. As students progress in coursework and build confidence in research skills, they conduct research independently with faculty support. We have a bi-weekly doctoral seminar, where
all students and faculty meet and discuss research and professional development topics of interest to students.







## Where Past Graduate Students Are Now  {-}


UGA QM graduates have had careers in academia (University of Miami, James Madison University), educational testing organizations (ETS, ACT), medical licensure boards (NCCPA, NBME), state departments of education, local school districts, research organizations, and corporations.



