
# University of Kansas {-}

## Brain, Behavior, and Quantitative Science Program {-}

 http://bbq.ku.edu/ 

## Program Mission  {-}


Faculty and students in the Brain, Behavior, and Quantitative Science program at KU seek a better understanding of human behavior through interdisciplinary approaches and translate that basic understanding to improve the development and well‐being of individuals in society. We work toward this goal by developing better models of behavior, cognition, and brain function through translational research and the creation of new computational and statistical tools that allow us to extract meaningful and useful conclusion from complex data.  



## Faculty and Research Interests  {-}


The Brain, Behavior, and Quantitative Science program has 7 affiliated faculty members in the department of Psychology. Program research interests include behavioral economics, cognitive neuroscience, cognitive science, developmental science, learning, and quantitative and computational methods. Faculty members recruiting students for the Fall 2022 year include Jeffrey Girard (interests in affective computing, machine learning, and Bayesian modeling), Tim Pleskac (interests in behavioral economics, computational models of human behavior and cognition), and Amber Watts (interests in health behaviors, prevention strategies, and bio-behavioral processes associated with cognitive decline & dementia).





## General Curriculum  {-}


We offer a single doctoral degree in Psychology; students admitted to this program enter with the expectation of continuing graduate study through the Ph.D. as the department does not admit terminal master's students. Although most applicants have majored in psychology as undergraduates, this is not required. 

The Ph.D. program in Brain, Behavior, and Quantitative Science provides instruction and research training for students pursuing careers in the academic, public, and private sectors that draw on the research and scholarly interests of the group. A key aspect of the program is that each student’s training plan is individually tailored and fit to each student’s personal goals. In general, though, a strong emphasis is placed on students developing a fundamental understanding of psychological theory, acquiring advanced statistical and computational skills and expertise, and learning how to apply this science to improve the development and/or well‐being of individuals in society. Toward this end, the program requires both coursework and constant involvement in the research endeavor, whether in the laboratory or in the field, and (where appropriate) active engagement in opportunities to translate basic science into practice or application.


## Admissions Criteria  {-}


Our admission criteria is based on a holistic evaluation of the application material. The application material consists of   
⦁	C.V.  
⦁	Statement of Purpose  
⦁	Undergraduate and where appropriate graduate transcripts  
⦁	GRE Scores (optional for 2022)  
⦁	TOEFEL Scores (for international students)  
⦁	Letters of recommendation  

As our program takes more of an apprentice model in training, we also assess fit between the applicant and the advisor/advisors the students wishes to work with. 

Our website is in the middle of transitioning to a new platform, but you can find some information on our older website here: https://bbq.ku.edu/

 


## Admissions Timeline  {-}


PhD applications are due on December 1, 2021 for admission in Fall 2022. A short list of applicants will be invited for online interviews in December and campus interviews in January. Admissions decisions will be made prior to April 15.



## Funding  {-}


Accepted students typically are offered either a teaching assistantship or research assistantship. Because of the importance of funding in academic research, the BBQ also supports and urges students to actively consider and pursue opportunities for external funding such as graduate research fellowships.


## Mentoring / Student Engagement Philosophy  {-}


The BBQ's takes an apprentice-style approach to training so there is both hands-on training working with faculty on set of research of projects and classroom instruction. 






## Where Past Graduate Students Are Now  {-}


The Brain, Behavior, and Quantitative Science Program is a new program in the Department of Psychology that began in earnest in 2019. It represents an integration of several different areas of psychology including cognition and cognitive neuroscience, developmental science, and quantitative and computational modeling. As such we are still establishing our track record of graduates. But, our aim is to train students in developing basic psychological science and translating that science into practice or application. 

Here are a sample of students trained by our faculty or have come from our program:  

⦁	Peter Kvam (Pleskac), Assistant Professor, University of Florida  
⦁	Christina Leuker (Pleskac), Research Scientist, Robert Koch Institute  
⦁	Zach Roman, Postdoctoral Researcher, University of Zurich  
⦁	Cynthia Siew (Vitevitch), Assistant Professor, National University of Singapore  
⦁	Nichol Castro (Vitevitch), Assistant Professor, University of Buffalo   




