
# University of Missouri {-}

## Statistics, Measurement, & Evaluation in Education Program  {-}

https://education.missouri.edu/educational-school-counseling-psychology/degrees-programs/statistics-measurement-evaluation-education/

## Program Mission  {-}
The Statistics, Measurement, and Evaluation in Education (SMEE) program at the University of Missouri aims to provide students with rigorous training in advanced statistical research methods, with primary emphasis on psychological measurement and causal inference. We are committed to providing graduate students with opportunities to explore their own interests in these fields, while also incorporating our student into the research and teaching that we conduct.



## Faculty and Research Interests  {-}
We have four tenure-track faculty members with interests in advanced psychometrics (e.g., item response theory, diagnostic classification modeling, mixture modeling), latent variable modeling (e.g., structural equation modeling, factor analysis), and causal inference methods (e.g., graphical causal modeling, causal discovery).




## General Curriculum  {-}
The SMEE program offers both PhD and Master’s tracks for graduate students, and we coordinate the College of Education and Human Development’s Graduate Research certificate in Quantitative Research.



## Admissions Criteria  {-}
⦁	Three letters of recommendation  
⦁	CV/resume  
⦁	Unofficial academic transcripts of all previous undergraduate and graduate work, with a minimum undergraduate GPA of 3.0 from an accredited institution in psychology, education, or a related major.  
⦁	Statement of purpose describing research interests and experiences in educational measurement, assessment, or evaluation.  
⦁	TOEFL for international students (preferred score of 580 for paper test, 92 iBT, IELTS 6.5 or higher).  


## Admissions Timeline  {-}

Applications are due January 15th, and decisions are typically made in early February and March




## Funding  {-}

Funding via both research and teaching assistantships is typically available, and most of these positions will include a tuition waiver along with a stipend. The department will typically guarantee such funding to all PhD students for their first year of study and has a long record of providing such funding to PhD students throughout their 4-5 years of study. The department also has a record of obtaining University supported fellowships and provides a limited number of departmental fellowships to qualified students.

## Mentoring / Student Engagement Philosophy  {-}

We place students at the center of our mentoring relationships and strive to craft an experience that connects to each student’s individual interest and career goals. We also ensure that each student gains opportunities to contribute to existing research and conduct their own studies, and we present them with opportunities to teach and interact with students in a learning setting. Thus, our graduate students gain key skills that can serve them in both academic and non-academic careers while ensuring their independence to pursue their own interests and possible career paths.


## Where Past Graduate Students Are Now  {-}

Graduates of our program have secured faculty positions at both research intensive and non- research-intensive universities and colleges. Graduates have also acquired positions with research centers and testing organizations.
