---
title: "University of Southern California"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Quantitative Methods and Computational Psychology Program https://dornsife.usc.edu/psyc/quantitative-methods/  {-}

## Program Mission  {-}
The program in Quantitative Methods and Computational Psychology (QMCP) at USC trains students in both the basics and the advances in methodological, statistical, and computational tools to study human behavior. Our program focuses on the development of strong research skills, including basic statistics, robust statistics, multivariate measurement, multilevel and longitudinal data analysis, experimental design and methods, decision making, cumulative reviews, behavior, and molecular genetics. We teach and encourage computer programming of all types (e.g., SAS, SPSS, R) as well as train students about new advances in computational modeling (LISREL, Mplus, CART, Keras). We emphasize the application of these research skills to matters of real-world importance needed for any topical area of behavioral science.






## Faculty and Research Interests  {-}
⦁	Joe Arvai: Judgment and decision-making about sustainability and the environment; decision support for public policy and consumer choice; tradeoffs across conflicting social economic and environmental; objectives internal consistency and decision quality; risk perception and communication. (Director, Wrigley Institute for Environmental Studies)  


⦁	Laura Baker: Statistical models of gene-environment interplay in human behavior, and the biological and social processes that lead to diversity. Longitudinal methods for understanding individual differences in both stability and change in traits and behaviors across development.  


⦁	Chris Beam: Population genetic studies of cognitive aging, dementia, personality, and psychopathology; social pain and grief; advanced quantitative methods  


⦁	Wändi de Bruine: Psychology of risk, behavioral decision making, age differences in decision-making competence and well-being, communications and behavior change interventions for promoting health, well-being, safety, and sustainability. (Co-Director, Behavioral Sciences Program, USC Schaeffer Center; Provost Professor of Public Policy, Psychology, and Behavioral Science, USC Price School of Public Policy; Behavioral Scientist, USC Center for Economic and Social Research, CESR).  


⦁	Morteza Dehghani: Social media analysis with direct applications to moral decision- making, group dynamics, and culture. Role of sacred values in intergroup conflict and negotiation. Computational cognitive modeling.  



⦁	Richard John (Area Head): Decision analysis and behavioral games. (Associate Director, USC Center for Risk and Economic Analysis of Threats and Emergencies, CREATE)  


⦁	Mark Lai: Statistical methods for adjusting measurement errors and biases. Multilevel and latent variable models for complex data. Psychometrics and Bayesian statistics.  


⦁	Carol Prescott: The primary goal of my research is to understand the genetic and environmental sources of individual differences in cognition and cognitive aging.  


⦁	Rand Wilcox: Robust methods aimed at correcting known problems associated with classic, routinely used techniques for comparing groups and studying associations. Included are various multivariate techniques such as principal components and outlier detection methods.  




## General Curriculum  {-}
Ph.D. only  
⦁	60 Units Minimum to Degree, which includes at least  
⦁	Six courses (24 units) in Quantitative Methods and Computational Psychology  
⦁	Three courses (16 units) in other areas of psychology  
⦁	Year 2: 2nd-year project  
⦁	Year 3-4: Qualifying exam  
⦁	Year 4-5: Dissertation  




## Admissions Criteria  {-}
We use a holistic admission procedure by considering applicants’ academic performance, coursework in research method and psychology, research experience and potentials, personal characteristics, and potential fit to the program. Applicants should submit the following  
⦁	Personal Statement  
⦁	Three Letters of Recommendation  
⦁	Official transcripts  
⦁	Resume/CV  
⦁	(For international applicants)   TOEFL/IELTS score  
.

## Admissions Timeline  {-}
Application deadline: December 1 Campus visit: January - February



## Funding  {-}
Two years of fellowship + three years funding on teaching/research assistantship.


## Mentoring / Student Engagement Philosophy  {-}
Students work closely with their primary advisor to develop an area of research expertise, while often also developing additional lines of research with other faculty in the department. We encourage our students to work within other areas of the department to gain additional skills and expertise such as neuroimaging techniques, aging research designs, social psychology experiments, cognitive survey research, and developmental principles.



## Where Past Graduate Students Are Now  {-}
⦁	Faculty position at research universities  
⦁	Research scientist at technology companies  
⦁	Statistician at private and public institutes  
⦁	Institutional research/student success analyst  
⦁	User experience, brand analytics, and product strategy researcher  

